use_frameworks!

platform :ios, '8.0'
FF_VER='4.3'
OpenSSL_VER='1.1.1h'

target 'FFmpegTutorial-iOS' do
  pod 'GDPerformanceView-Swift'
  pod 'FFmpegTutorial', :path => '../../'
  puts "will install MRFFmpeg#{FF_VER}"
  # pod 'MRFFmpegPod', :podspec => "https://raw.githubusercontent.com/debugly/MRFFToolChainPod/master/MRFFmpeg#{FF_3_4_7}.podspec"
  pod 'MRFFmpegPod',  :podspec => "https://ifoxdev.hd.sohu.com/ffpods/MRFFmpeg#{FF_VER}.podspec"
  pod 'MROpenSSLPod', :podspec => "https://ifoxdev.hd.sohu.com/ffpods/MROpenSSL#{OpenSSL_VER}.podspec"
end
