use_frameworks!

platform :ios, '11.0'

target 'FFmpegTutorial-iOS' do
  pod 'FFmpegTutorial', :path => '../../'
end

pre_install do |installer|
  this_dir = File.dirname(File.realpath(__FILE__))
  install_shell = File.expand_path('../../install-pre-any.sh', this_dir)
  # puts "#{install_shell}"
  if system "#{install_shell} ios all" 
    puts "依赖库安装成功！"
  else
    puts
    puts "⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️  依赖库安装失败，请重新运行 pod install ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️"
    puts "⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️  依赖库安装失败，请重新运行 pod install ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️"
    puts "⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️  依赖库安装失败，请重新运行 pod install ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️"
    puts
  end
end
