use_frameworks!

platform :osx, '10.11'
FF_VER='4.3'
OpenSSL_VER='1.1.1h'

target 'FFmpegTutorial-macOS' do
  pod 'FFmpegTutorial',:path => '../../'
  pod 'MROpenSSLPod',  :podspec => "https://ifoxdev.hd.sohu.com/ffpods/MROpenSSL#{OpenSSL_VER}.podspec"
  pod 'MRFFmpegPod',   :podspec => "https://ifoxdev.hd.sohu.com/ffpods/MRFFmpeg#{FF_VER}.podspec"
end
